### ISSUE TITLE
Calculo de Taxa de IRS para Horas Extra no mês em que é atingida e ultrapassada a 101ª hora

### ISSUE THREAD

**Issue by patricialmeida** [assoft-portugal/wg-rh-pt#13]
### Questão

Afetação do valor das Horas Extra, até às 100 horas e depois das 100

### Exemplos

Se num mês o colaborador fizer 31,5 HE, divididas pelas seguintes tipologias:

HE01 - Trabalho suplementar (1ª hora) - 11,5H no valor de 66,41 € 
HE02 - Trabalho suplementar (horas seguintes) - 8,5 H no valor de 54 € 
HE03 - Trabalho suplementar (Dias Descanso) - 11 H no valor de 76.23 €
HE04 - Trabalho suplementar (HE Noturnas) - 0,5 H no valor de 3.75€

Se no acumulado ao mês anterior tiver um total de 95 HE trabalhadas, que valores das horas acima devem ser taxadas a 100%, ou a 50% da taxa efetiva?

É viável fazer um valor médio da HE? Tendo um total de valor de HE de 200,39€ para 31,5 HE trabalhadas no mês?

Poderíamos aplicar os 100% da Taxa efetiva de IRS ao valor de (200.39/31.5) * (100-95) HE --> (as 5 HE que faltavam para as 100)
e aplicar os 50% da taxa efetiva de IRS ao restante valor (200.39/31.5) * (31,5 - 5)?

**Comment by patricialmeida** [comment]
Dado que o Artigo 268º - Pagamento de trabalho suplementar do Código do Trabalho foi agora alterado pela lei nº 13 / 2023 de 3 de Abril e que está prestes a entrar em vigor, esta questão deixa de fazer sentido dado que o trabalho suplementar superior a 100 horas anuais é pago com percentagens diferentes relativamente às primeiras 100 horas, e por isso terá que ter codificação própria para valorização diferente.
![image](https://github.com/assoft-portugal/wg-rh-pt/assets/69452646/3dd49272-818e-461d-9381-d413ac2c8cdc)

**Comment by cryptolopes** [comment]
Não vamos documentar por agora.
